---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-c
  labels:
    app: wordpress-c
spec:
  ports:
    - port: 80
  selector:
    app: wordpress-c
    tier: frontend-c
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wpc-pv-claim
  labels:
    app: wordpress-c
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1    # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress-c
  labels:
    app: wordpress-c
spec:
  selector:
    matchLabels:
      app: wordpress-c
      tier: frontend-c
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-c
        tier: frontend-c
    spec:
      containers:
        - image: wordpress:latest
          name: wordpress-c
          env:
            - name: WORDPRESS_DB_HOST
              value: <<ENTER YOUR DB HOST>>:<<ENTER DB PORT>>
            - name: WORDPRESS_DB_USER
              value: <<ENTER YOUR DB USERNAME>>
            - name: WORDPRESS_DB_PASSWORD
              value: <<ENTER YOUR DB PASSWORD FROM COMPOSE>>
          ports:
            - containerPort: 80
              name: wordpress-c
          volumeMounts:
            - name: wordpress-c-persistent-storage
              mountPath: /var/www/html
      volumes:
        - name: wordpress-c-persistent-storage
          persistentVolumeClaim:
            claimName: wpc-pv-claim
